### ISSUE TITLE
very good i could already go shit 

### ISSUE THREAD

**Issue by notadminnn** [PollarEx/Discord-Server-Cloner#1]
Traceback (most recent call last):
  File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 249, in <module>
    data    = Scrape(token, id).get_data()
  File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 43, in get_data
    info = self.get_info()
  File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 40, in get_info
    return self.do_request(self.baseurl)
  File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 34, in do_request
    ).json()
  File "/home/runner/UnevenPerfumedMegahertz/.pythonlibs/lib/python3.10/site-packages/httpx/_models.py", line 762, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PollarEx** [comment]
> Traceback (most recent call last): File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 249, in data = Scrape(token, id).get_data() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 43, in get_data info = self.get_info() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 40, in get_info return self.do_request(self.baseurl) File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 34, in do_request ).json() File "/home/runner/UnevenPerfumedMegahertz/.pythonlibs/lib/python3.10/site-packages/httpx/_models.py", line 762, in json return jsonlib.loads(self.content, **kwargs) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

You can follow the steps below to find and fix the source of the error:

Check line 249 in main.py:

First, examine the code at line 249 in /home/runner/UnevenPerfumedMegahertz/a/main.py. This line appears to create an instance of the Scrape class and then calls the get_data function. To find the source of this error, check this line and check which parameters are used and whether these parameters are valid.
Check line 43 in main.py:

Examine line 43 in the get_data function. This line appears to call the get_info function. Check the operations within this function and check for any possible errors or omissions here.
Check line 40 in main.py:

Examine line 40 in the get_info function. This line seems to call the do_request function. Check the operations inside this function and determine the cause of this error chain.
Check line 34 in main.py:

Examine line 34 in the do_request function. This line looks like it's getting a JSON response by making the HTTP request. Check the URL from which this request was made and see if the response contains a JSON document as expected.
Examine the HTTP request result:

If the HTTP request returns an error status or an unexpected response, you can handle this situation and look for a solution if necessary by checking the documentation of the library used for the HTTP request.
Add error checking if necessary:

You can handle unexpected situations by adding error checking in your code if necessary. For example, you can specify how your program should behave in case of JSONDecodeError.
By following these steps, you can identify the source of the error and take steps to correct it

**Comment by notadminnn** [comment]
> > Traceback (most recent call last): File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 249, in data = Scrape(token, id).get_data() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 43, in get_data info = self.get_info() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 40, in get_info return self.do_request(self.baseurl) File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 34, in do_request ).json() File "/home/runner/UnevenPerfumedMegahertz/.pythonlibs/lib/python3.10/site-packages/httpx/_models.py", line 762, in json return jsonlib.loads(self.content, **kwargs) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> You can follow the steps below to find and fix the source of the error:
> 
> Check line 249 in main.py:
> 
> First, examine the code at line 249 in /home/runner/UnevenPerfumedMegahertz/a/main.py. This line appears to create an instance of the Scrape class and then calls the get_data function. To find the source of this error, check this line and check which parameters are used and whether these parameters are valid. Check line 43 in main.py:
> 
> Examine line 43 in the get_data function. This line appears to call the get_info function. Check the operations within this function and check for any possible errors or omissions here. Check line 40 in main.py:
> 
> Examine line 40 in the get_info function. This line seems to call the do_request function. Check the operations inside this function and determine the cause of this error chain. Check line 34 in main.py:
> 
> Examine line 34 in the do_request function. This line looks like it's getting a JSON response by making the HTTP request. Check the URL from which this request was made and see if the response contains a JSON document as expected. Examine the HTTP request result:
> 
> If the HTTP request returns an error status or an unexpected response, you can handle this situation and look for a solution if necessary by checking the documentation of the library used for the HTTP request. Add error checking if necessary:
> 
> You can handle unexpected situations by adding error checking in your code if necessary. For example, you can specify how your program should behave in case of JSONDecodeError. By following these steps, you can identify the source of the error and take steps to correct it

ur the owner go fix your code

**Comment by notadminnn** [comment]
> > > Traceback (most recent call last): File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 249, in data = Scrape(token, id).get_data() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 43, in get_data info = self.get_info() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 40, in get_info return self.do_request(self.baseurl) File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 34, in do_request ).json() File "/home/runner/UnevenPerfumedMegahertz/.pythonlibs/lib/python3.10/site-packages/httpx/_models.py", line 762, in json return jsonlib.loads(self.content, **kwargs) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > 
> > 
> > You can follow the steps below to find and fix the source of the error:
> > Check line 249 in main.py:
> > First, examine the code at line 249 in /home/runner/UnevenPerfumedMegahertz/a/main.py. This line appears to create an instance of the Scrape class and then calls the get_data function. To find the source of this error, check this line and check which parameters are used and whether these parameters are valid. Check line 43 in main.py:
> > Examine line 43 in the get_data function. This line appears to call the get_info function. Check the operations within this function and check for any possible errors or omissions here. Check line 40 in main.py:
> > Examine line 40 in the get_info function. This line seems to call the do_request function. Check the operations inside this function and determine the cause of this error chain. Check line 34 in main.py:
> > Examine line 34 in the do_request function. This line looks like it's getting a JSON response by making the HTTP request. Check the URL from which this request was made and see if the response contains a JSON document as expected. Examine the HTTP request result:
> > If the HTTP request returns an error status or an unexpected response, you can handle this situation and look for a solution if necessary by checking the documentation of the library used for the HTTP request. Add error checking if necessary:
> > You can handle unexpected situations by adding error checking in your code if necessary. For example, you can specify how your program should behave in case of JSONDecodeError. By following these steps, you can identify the source of the error and take steps to correct it
> 
> ur the owner go fix your code

nvm let me just go fix the code for you using a bit of ai

**Comment by PollarEx** [comment]
> > > > Traceback (most recent call last): File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 249, in data = Scrape(token, id).get_data() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 43, in get_data info = self.get_info() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 40, in get_info return self.do_request(self.baseurl) File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 34, in do_request ).json() File "/home/runner/UnevenPerfumedMegahertz/.pythonlibs/lib/python3.10/site-packages/httpx/_models.py", line 762, in json return jsonlib.loads(self.content, **kwargs) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > > 
> > > 
> > > You can follow the steps below to find and fix the source of the error:
> > > Check line 249 in main.py:
> > > First, examine the code at line 249 in /home/runner/UnevenPerfumedMegahertz/a/main.py. This line appears to create an instance of the Scrape class and then calls the get_data function. To find the source of this error, check this line and check which parameters are used and whether these parameters are valid. Check line 43 in main.py:
> > > Examine line 43 in the get_data function. This line appears to call the get_info function. Check the operations within this function and check for any possible errors or omissions here. Check line 40 in main.py:
> > > Examine line 40 in the get_info function. This line seems to call the do_request function. Check the operations inside this function and determine the cause of this error chain. Check line 34 in main.py:
> > > Examine line 34 in the do_request function. This line looks like it's getting a JSON response by making the HTTP request. Check the URL from which this request was made and see if the response contains a JSON document as expected. Examine the HTTP request result:
> > > If the HTTP request returns an error status or an unexpected response, you can handle this situation and look for a solution if necessary by checking the documentation of the library used for the HTTP request. Add error checking if necessary:
> > > You can handle unexpected situations by adding error checking in your code if necessary. For example, you can specify how your program should behave in case of JSONDecodeError. By following these steps, you can identify the source of the error and take steps to correct it
> > 
> > 
> > ur the owner go fix your code
> 
> nvm let me just go fix the code for you using a bit of ai

I'm not at home right now, I'll fix it when I get home

**Comment by PollarEx** [comment]
> > > > Traceback (most recent call last): File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 249, in data = Scrape(token, id).get_data() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 43, in get_data info = self.get_info() File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 40, in get_info return self.do_request(self.baseurl) File "/home/runner/UnevenPerfumedMegahertz/a/main.py", line 34, in do_request ).json() File "/home/runner/UnevenPerfumedMegahertz/.pythonlibs/lib/python3.10/site-packages/httpx/_models.py", line 762, in json return jsonlib.loads(self.content, **kwargs) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > > 
> > > 
> > > You can follow the steps below to find and fix the source of the error:
> > > Check line 249 in main.py:
> > > First, examine the code at line 249 in /home/runner/UnevenPerfumedMegahertz/a/main.py. This line appears to create an instance of the Scrape class and then calls the get_data function. To find the source of this error, check this line and check which parameters are used and whether these parameters are valid. Check line 43 in main.py:
> > > Examine line 43 in the get_data function. This line appears to call the get_info function. Check the operations within this function and check for any possible errors or omissions here. Check line 40 in main.py:
> > > Examine line 40 in the get_info function. This line seems to call the do_request function. Check the operations inside this function and determine the cause of this error chain. Check line 34 in main.py:
> > > Examine line 34 in the do_request function. This line looks like it's getting a JSON response by making the HTTP request. Check the URL from which this request was made and see if the response contains a JSON document as expected. Examine the HTTP request result:
> > > If the HTTP request returns an error status or an unexpected response, you can handle this situation and look for a solution if necessary by checking the documentation of the library used for the HTTP request. Add error checking if necessary:
> > > You can handle unexpected situations by adding error checking in your code if necessary. For example, you can specify how your program should behave in case of JSONDecodeError. By following these steps, you can identify the source of the error and take steps to correct it
> > 
> > 
> > ur the owner go fix your code
> 
> nvm let me just go fix the code for you using a bit of ai

**The errors have been resolved, the code has been optimized, you can run the start.bat file and see it. Do not forget to fill in the config.json. Have a nice day.**

**Comment by DYREX-FPV** [comment]
Thats a trojan
